name: Continuous Integration
on:
 pull_request:
   types: [opened, synchronize, reopened]
 push:
   branches:
     - master

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
    - name: ref
      run: echo ${{ github.ref }}
    - name: event_name
      run: echo ${{ github.event_name }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.4'
    - name: lint
      uses: golangci/golangci-lint-action@v2
    - name: vet
      run: make vet
    - name: test
      run: make test
    - name: fmt
      run: make fmt-check
    - name: build
      run: make build
